import { integer, numeric, pgTable, text, timestamp, varchar } from "drizzle-orm/pg-core";
import { usersTable } from "./user.schema";

export const collateralTable = pgTable("collateral", {
     id: text("id").primaryKey(), // Usually UUIDs generated by the application
     userId: text("user_id").notNull().unique(), // Assuming we have a users table with text UUIDs
     availableBalance: numeric("available_balance", { precision: 30, scale: 0 }).notNull().default("0"),
     locked: numeric("locked", { precision: 30, scale: 0 }).notNull().default("0"),
     updatedAt: timestamp("updated_at").defaultNow(),
   });
